version: "2"

services:
    service-a:
        build: ./service-a
        ports:
            - "8080:8080"
            - "9229:9229"
        depends_on:
            - service-b
            - mycache
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}

    service-b:
        build: ./service-b
        expose:
            - "80"
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}

    mycache:
        image: redis:alpine
        expose:
            - "6379"
